name: Scan Actions Repositories

on:
  workflow_dispatch:
  pull_request:
  
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: jenseng/dynamic-uses@v1
        with:
          # now you can use expressions 🥳
          uses: chocrates/actions-governance@${{ github.sha }}
          # the `with` needs to be converted to a valid json string
          with: '{ "token": ${{ secrets.ORG_TOKEN }}, "organization": "chocrates-test-org" }'
