name: Scan Actions Repositories

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: chocrates-test-org/actions-governance@main
        with:
          token: ${{ secrets.ORG_TOKEN }}
          organization: 'chocrates-test-org'
