name: Scan Actions Repositories

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: |
          node scan-repos.js -t ${{ secrets.ORG_TOKEN }} -o ${{ github.repository_owner }} | 
            jq -c '.[]' | 
            while read i; do 
              # Set json object as bash variables
              eval $(echo $i | jq -r '. | to_entries | .[] | .key + "=" + (.value | @sh)')

              if [[ $scanning_enabled != true || $scanning_workflow != true || $all_alerts_closed != true ]]; then
                if [[ -z "$description" ]]; then
                  echo "Description is empty, can't sync upstream to $name"
                else
                  git clone https://${{ secrets.ORG_TOKEN }}@github.com/${{ github.repository_owner }}/$name.git
                  cd $name
                  curl https://raw.githubusercontent.com/repo-sync/github-sync/3832fe8e2be32372e1b3970bbae8e7079edeec88/github-sync.sh > github-sync.sh
                  pwd
                  ls -al
                  GITHUB_TOKEN="${{ secrets.ORG_TOKEN }}" GITHUB_REPOSITORY="${{ github.repository_owner }}/$name" bash github-sync.sh $description "$default_branch:$default_branch-sync"
                  gh pr --repo "${{ github.repository_owner }}/$name" create --title "Merge Upstream" --body "This repository is non-compliant.  This PR has been automatically generated to help you merge Upstream in hopes that it helps come in to compliance" --base $default_branch --head "$default_branch-sync"
                  # node notify-non-compliance -t ${{ secrets.ORG_TOKEN }} -o ${{ github.repository_owner }} -r $name
                fi
              else
                echo "don't nag"
              fi
            done
