name: Scan Actions Repositories

on:
  schedule:
    - cron: '13 17 * * *'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: node scan-repos.js -t ${{ secrets.ORG_TOKEN }} -o chocrates-test-org -r garbage
