name: Scan Actions Repositories

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: chocrates/actions-governance@main
        with:
          token: ${{ secrets.ORG_TOKEN }}
          organization: 'chocrates-test-org'
