name: Scan Actions Repositories

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: |
          node scan-repos.js -t ${{ secrets.ORG_TOKEN }} -o ${{ github.repository_owner }} | 
            jq -c '.[]' | 
            while read i; do 
              eval $(echo $i | jq -r '. | to_entries | .[] | .key + "=" + (.value | @sh)')
              env
              if [[ $scanning_enabled != true || $scanning_workflow != true || $all_alerts_closed != true ]]; then
                echo "nag"
              else
                echo "don't nag"
              fi
            done
          
